# config.yaml

# Data paths
data:
  normal_dir: "data/normal"
  abnormal_dir: "data/abnormal"
  preprocessed_train_normal_dir: "preprocessed_data/train_normal"
  preprocessed_train_abnormal_dir: "preprocessed_data/train_abnormal"
  preprocessed_val_normal_dir: "preprocessed_data/val_normal"
  preprocessed_val_abnormal_dir: "preprocessed_data/val_abnormal"
  preprocessed_test_normal_dir: "preprocessed_data/test_normal"
  preprocessed_test_abnormal_dir: "preprocessed_data/test_abnormal"

# Model paths
saved_models:
  model_dir: "saved_models"
  model_filename: "vqvae_best.h5"

#Model settings
model:
  input_shape: [17, 1387, 1]
  shuffle: true
  embedding_dim: 128
  num_embeddings: 256


# Results paths
results:
  evals_dir: "results/evals"
  reconstructed_dir: "results/reconstructed"

# Preprocessing settings
preprocessing:
  sample_rate: 2000
  target_rate: 1000
  chunk_size: 12.5
  stft_n_fft: 64
  stft_hop_length: 3

# Training settings
training:
  path: saved_models
  batch_size: 32
  learning_rate: 0.0001
  epochs: 100
  latent_dim: 256
  commitment_cost: 0.25
  decay_steps: 50000
  decay_rate: 0.5
  beta1: 0.9
  beta2: 0.999
  early_stopping_patience: 10
  validation_split: 0.2 

# Evaluation settings
evaluation:
  mse_threshold: 0.0005  # Mean Squared Error threshold for evaluation
  ssim_threshold: 0.75  # SSIM threshold for image quality evaluation

# Inference settings
inference:
  output_dir: "results/reconstructed"  # Output directory for reconstructed images
