# config.yaml

# Data paths
data:
  normal_dir: "data/normal"
  abnormal_dir: "data/abnormal"
  preprocessed_normal_dir: "preprocessed_data/normal"
  preprocessed_abnormal_dir: "preprocessed_data/abnormal"

# Model paths
saved_models:
  model_dir: "saved_models"
  model_filename: "vqvae_best.h5"

#Model settings
model:
  input_shape: [128, 128, 1]
  shuffle: true
  embedding_dim: 128
  num_embeddings: 256


# Results paths
results:
  evals_dir: "results/evals"
  reconstructed_dir: "results/reconstructed"

# Preprocessing settings
preprocessing:
  chunk_size: 4    # Length of each chunk in seconds
  sample_rate: 2000  # Sample rate for audio
  mel_n_fft: 512   # FFT size for Mel spectrogram
  mel_win_length: 512  # Window size for Mel spectrogram
  mel_hop_length: 128   # Hop length for Mel spectrogram
  mel_num_mels: 512  # Number of Mel bins
  gammatone: True    # Use Gammatone filterbank

# Training settings
training:
  path: saved_models
  batch_size: 32
  learning_rate: 0.0001
  epochs: 100
  latent_dim: 256
  commitment_cost: 0.25
  decay_steps: 50000
  decay_rate: 0.5
  beta1: 0.9
  beta2: 0.999
  early_stopping_patience: 10
  validation_split: 0.2 

# Evaluation settings
evaluation:
  mse_threshold: 0.01  # Mean Squared Error threshold for evaluation
  ssim_threshold: 0.75  # SSIM threshold for image quality evaluation

# Inference settings
inference:
  output_dir: "results/reconstructed"  # Output directory for reconstructed images
